#!/bin/bash

set -e

apply() {
	./vpc apply
	./consul apply
	./monitoring apply
	./chatops apply
}

destroy() {
	./chatops destroy
	./monitoring destroy
	./consul destroy
	./vpc destroy
}

case "$1" in
  destroy)
    destroy
    ;;
  apply)
    apply
    ;;
  *)
    echo "Usage: $0 {apply|destroy}"
esac