#!/bin/bash

apply() {
	terraform apply -auto-approve -target=aws_security_group.consul

	terraform apply -auto-approve -target=aws_route.consul
	terraform apply -auto-approve -target=aws_route_table_association.consul
	
	terraform apply -auto-approve -target=aws_instance.consul-leader
	terraform apply -auto-approve -target=aws_ecs_service.consul-leader
	terraform apply -auto-approve -target=aws_elb_attachment.consul-leader
	
	terraform apply -auto-approve -target=aws_instance.consul-server
	terraform apply -auto-approve -target=aws_ecs_service.consul-server
	terraform apply -auto-approve -target=aws_elb_attachment.consul-server
}

destroy() {
	terraform destroy -force -target=aws_elb_attachment.consul-leader
	terraform destroy -force -target=aws_ecs_service.consul-leader
	terraform destroy -force -target=aws_instance.consul-leader
	
	terraform destroy -force -target=aws_elb_attachment.consul-server
	terraform destroy -force -target=aws_ecs_service.consul-server
	terraform destroy -force -target=aws_instance.consul-server

	terraform destroy -force -target=aws_route_table_association.consul
	terraform destroy -force -target=aws_route.consul
}

case "$1" in
  destroy)
    destroy
    ;;
  apply)
    apply
    ;;
  *)
    echo "Usage: $0 {apply|destroy}"
esac