#!/bin/bash

environment="$(git symbolic-ref HEAD 2>/dev/null)" || environment="(unnamed branch)"
environment=${environment##refs/heads/}

if [[ $branch_name == "master" ]]; then
	environment=poc
	 
fi

