#!/bin/bash

set -e

apply() {

	terraform apply -auto-approve -target=aws_security_group.monitoring

	terraform apply -auto-approve -target=aws_instance.graphite
	terraform apply -auto-approve -target=aws_volume_attachment.monitoring
	terraform apply -auto-approve -target=aws_ecs_service.graphite

	terraform apply -auto-approve -target=aws_route.monitoring
	terraform apply -auto-approve -target=aws_route_table_association.monitoring
	terraform apply -auto-approve -target=aws_elb_attachment.grafana

	terraform apply -auto-approve -target=aws_route53_record.grafana
}

destroy() {
	terraform destroy -force -target=aws_elb_attachment.grafana
	terraform destroy -force -target=aws_route_table_association.monitoring
	terraform destroy -force -target=aws_route.monitoring

	terraform destroy -force -target=aws_ecs_service.graphite
	terraform destroy -force -target=aws_volume_attachment.monitoring
	terraform destroy -force -target=aws_instance.graphite

	terraform destroy -force -target=aws_security_group.monitoring
}

case "$1" in
  destroy)
    destroy
    ;;
  apply)
    apply
    ;;
  *)
    echo "Usage: $0 {apply|destroy}"
esac