#!/bin/bash

apply() {
	terraform apply -auto-approve -target=aws_route.weblayer
	terraform apply -auto-approve -target=aws_route_table_association.weblayer
	
	terraform apply -auto-approve -target=aws_instance.weblayer
	terraform apply -auto-approve -target=aws_ecs_service.weblayer
	terraform apply -auto-approve -target=aws_elb_attachment.weblayer
}

destroy() {
	terraform destroy -force -target=aws_elb_attachment.weblayer
	terraform destroy -force -target=aws_ecs_service.weblayer
	terraform destroy -force -target=aws_instance.weblayer

	terraform destroy -force -target=aws_route_table_association.weblayer
	terraform destroy -force -target=aws_route.weblayer
	
}

case "$1" in
  destroy)
    destroy
    ;;
  apply)
    apply
    ;;
  *)
    echo "Usage: $0 {apply|destroy}"
esac